/**
 * Seed canonical listing taxonomy into croww-live-2026.
 * Explicitly guards against accidental execution; requires --confirm-production.
 */
const { PRODUCTION_PROJECT, assertProjectAllowed } = require('../functions/scripts/projectGuard');
const { getDoc, setDoc, patchDoc, listCollection } = require('../functions/scripts/cliFirestore');

const CANONICAL_TAXONOMY_SEEDS = [
    // ─── 1. Active Stay Categories ──────────────────────────────────────
    {
        id: 'bed',
        typeId: 'bed',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Bed',
        shortLabel: 'Bed',
        shortDescription: 'Single bed space in a shared room or hostel',
        description: 'Single bed space in a shared room or hostel',
        icon: 'bed-outline',
        status: 'ACTIVE',
        displayOrder: 1,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'shared_room',
        typeId: 'shared_room',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Shared Room',
        shortLabel: 'Shared Room',
        shortDescription: 'Shared bedroom with 1 or 2 roommates',
        description: 'Shared bedroom with 1 or 2 roommates',
        icon: 'people-outline',
        status: 'ACTIVE',
        displayOrder: 2,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'private_room',
        typeId: 'private_room',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Private Room',
        shortLabel: 'Private Room',
        shortDescription: 'Independent private bedroom in an apartment or house',
        description: 'Independent private bedroom in an apartment or house',
        icon: 'door-closed-outline',
        status: 'ACTIVE',
        displayOrder: 3,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'pg',
        typeId: 'pg',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'PG',
        shortLabel: 'PG',
        shortDescription: 'Paying guest accommodation with food & housekeeping',
        description: 'Paying guest accommodation with food & housekeeping',
        icon: 'home-outline',
        status: 'ACTIVE',
        displayOrder: 4,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'foodType', 'furnishing', 'attachedBathroom', 'genderPreference', 'rules', 'amenities'],
    },
    {
        id: 'coliving',
        typeId: 'coliving',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Co-living',
        shortLabel: 'Co-living',
        shortDescription: 'Fully managed community living with modern amenities',
        description: 'Fully managed community living with modern amenities',
        icon: 'business-outline',
        status: 'ACTIVE',
        displayOrder: 5,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'coworkingSpace', 'furnishing', 'attachedBathroom', 'amenities'],
    },
    {
        id: 'roommate_replacement',
        typeId: 'roommate_replacement',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Roommate Replacement',
        shortLabel: 'Roommate Replacement',
        shortDescription: 'Take over an existing tenancy or room in a shared flat',
        description: 'Take over an existing tenancy or room in a shared flat',
        icon: 'swap-horizontal-outline',
        status: 'ACTIVE',
        displayOrder: 6,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'availableFrom'],
        optionalFields: ['totalRoommates', 'genderPreference', 'furnishing', 'leaseEndDate', 'amenities'],
    },

    // ─── 2. Future Residential Categories (Inactive / postingEnabled: false) ──
    {
        id: '1bhk',
        typeId: '1bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: '1 BHK',
        shortLabel: '1 BHK',
        shortDescription: '1 Bedroom Hall Kitchen Apartment or House',
        description: '1 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 7,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['furnishing', 'bathrooms', 'parking', 'floor', 'amenities'],
    },
    {
        id: '2bhk',
        typeId: '2bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: '2 BHK',
        shortLabel: '2 BHK',
        shortDescription: '2 Bedroom Hall Kitchen Apartment or House',
        description: '2 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 8,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['furnishing', 'bathrooms', 'parking', 'floor', 'amenities'],
    },
    {
        id: '3bhk',
        typeId: '3bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: '3 BHK',
        shortLabel: '3 BHK',
        shortDescription: '3 Bedroom Hall Kitchen Apartment or House',
        description: '3 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 9,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['furnishing', 'bathrooms', 'parking', 'floor', 'amenities'],
    },
    {
        id: '4bhk',
        typeId: '4bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: '4 BHK',
        shortLabel: '4 BHK',
        shortDescription: '4 Bedroom Hall Kitchen Luxury Apartment or House',
        description: '4 Bedroom Hall Kitchen Luxury Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 10,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['furnishing', 'bathrooms', 'parking', 'floor', 'amenities'],
    },
    {
        id: 'villa',
        typeId: 'villa',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Villa',
        shortLabel: 'Villa',
        shortDescription: 'Independent villa or gated community house',
        description: 'Independent villa or gated community house',
        icon: 'business-outline',
        status: 'INACTIVE',
        displayOrder: 11,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'plotArea', 'availableFrom'],
        optionalFields: ['bedrooms', 'bathrooms', 'furnishing', 'parking', 'amenities'],
    },
    {
        id: 'independent_house',
        typeId: 'independent_house',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Independent House',
        shortLabel: 'Ind. House',
        shortDescription: 'Standalone individual residential house',
        description: 'Standalone individual residential house',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 12,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['plotArea', 'bedrooms', 'bathrooms', 'parking', 'floors', 'amenities'],
    },
    {
        id: 'apartment',
        typeId: 'apartment',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Apartment',
        shortLabel: 'Apartment',
        shortDescription: 'Residential apartment in a multi-story building',
        description: 'Residential apartment in a multi-story building',
        icon: 'business-outline',
        status: 'INACTIVE',
        displayOrder: 13,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'deposit', 'builtUpArea', 'availableFrom'],
        optionalFields: ['bedrooms', 'bathrooms', 'floor', 'totalFloors', 'parking', 'amenities'],
    },

    // ─── 3. Land / Plot Categories ──────────────────────────────────────
    {
        id: 'plot',
        typeId: 'plot',
        parentCategory: 'land',
        parentCategoryLabel: 'Land & Plots',
        section: 'sale',
        displayName: 'Plot',
        shortLabel: 'Plot',
        shortDescription: 'Residential or commercial layout land / plot',
        description: 'Residential or commercial layout land / plot',
        icon: 'map-outline',
        status: 'INACTIVE',
        displayOrder: 14,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: false,
        saleEnabled: true,
        requiredFields: ['askingPrice', 'plotArea', 'boundaryWall'],
        optionalFields: ['gatedCommunity', 'approvals', 'facing', 'cornerPlot'],
    },

    // ─── 4. Commercial Categories (Inactive / postingEnabled: false) ────
    {
        id: 'office',
        typeId: 'office',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Office',
        shortLabel: 'Office',
        shortDescription: 'Commercial office space or tech park unit',
        description: 'Commercial office space or tech park unit',
        icon: 'briefcase-outline',
        status: 'INACTIVE',
        displayOrder: 15,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['seats', 'cabins', 'conferenceRooms', 'furnishing', 'amenities'],
    },
    {
        id: 'shop',
        typeId: 'shop',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Shop',
        shortLabel: 'Shop',
        shortDescription: 'Retail shop, showroom, or boutique outlet',
        description: 'Retail shop, showroom, or boutique outlet',
        icon: 'cart-outline',
        status: 'INACTIVE',
        displayOrder: 16,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['mainRoadFacing', 'carpetArea', 'parking', 'amenities'],
    },
    {
        id: 'commercial_space',
        typeId: 'commercial_space',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Commercial Space',
        shortLabel: 'Comm. Space',
        shortDescription: 'Bare shell or warm shell commercial space',
        description: 'Bare shell or warm shell commercial space',
        icon: 'business-outline',
        status: 'INACTIVE',
        displayOrder: 17,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'floor', 'amenities'],
    },
    {
        id: 'warehouse',
        typeId: 'warehouse',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Warehouse',
        shortLabel: 'Warehouse',
        shortDescription: 'Commercial warehouse or storage godown',
        description: 'Commercial warehouse or storage godown',
        icon: 'cube-outline',
        status: 'INACTIVE',
        displayOrder: 18,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'ceilingHeight', 'parking', 'amenities'],
    },
];

async function seedProductionTaxonomy() {
    assertProjectAllowed({ apply: true });
    const projectId = PRODUCTION_PROJECT;
    console.log(`[seedProductionTaxonomy] Seeding canonical taxonomy to PRODUCTION (${projectId})...`);

    const now = new Date().toISOString();

    for (const item of CANONICAL_TAXONOMY_SEEDS) {
        const docPath = `listingTaxonomy/${item.id}`;
        const existing = await getDoc(projectId, docPath);

        const docPayload = {
            ...item,
            updatedAt: now,
            updatedBy: 'production-seed-script',
        };

        if (existing.exists) {
            await patchDoc(projectId, docPath, docPayload);
            console.log(`  ✔ Updated: ${item.id} (${item.displayName}) [${item.status}]`);
        } else {
            await setDoc(projectId, docPath, {
                ...docPayload,
                createdAt: now,
            });
            console.log(`  ✔ Created: ${item.id} (${item.displayName}) [${item.status}]`);
        }
    }

    // Verify
    const all = await listCollection(projectId, 'listingTaxonomy');
    console.log(`[seedProductionTaxonomy] Complete! Total documents: ${all.length}`);
    const active = all.filter((d) => d.data.status === 'ACTIVE');
    const inactive = all.filter((d) => d.data.status === 'INACTIVE');
    console.log(`  Active (${active.length}): ${active.map((d) => d.id).join(', ')}`);
    console.log(`  Inactive (${inactive.length}): ${inactive.map((d) => d.id).join(', ')}`);
}

seedProductionTaxonomy().catch((err) => {
    console.error('[seedProductionTaxonomy] Failed:', err);
    process.exit(1);
});
