/**
 * Seed canonical listing taxonomy into croww-staging-2026.
 * Guaranteed to only target croww-staging-2026.
 */
const { assertStagingOnly } = require('../functions/scripts/projectGuard');
const { setDoc, getDoc, listCollection } = require('../functions/scripts/cliFirestore');

const CANONICAL_TAXONOMY_SEEDS = [
    // ─── 1. Active Stay Categories ──────────────────────────────────────
    {
        id: 'bed',
        typeId: 'bed',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Bed',
        shortLabel: 'Bed',
        shortDescription: 'Single bed space in a shared room or hostel',
        description: 'Single bed space in a shared room or hostel',
        icon: 'bed-outline',
        status: 'ACTIVE',
        displayOrder: 1,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'shared_room',
        typeId: 'shared_room',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Shared Room',
        shortLabel: 'Shared Room',
        shortDescription: 'Shared bedroom with 1 or 2 roommates',
        description: 'Shared bedroom with 1 or 2 roommates',
        icon: 'people-outline',
        status: 'ACTIVE',
        displayOrder: 2,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'private_room',
        typeId: 'private_room',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Private Room',
        shortLabel: 'Private Room',
        shortDescription: 'Independent private bedroom in an apartment or house',
        description: 'Independent private bedroom in an apartment or house',
        icon: 'key-outline',
        status: 'ACTIVE',
        displayOrder: 3,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'availableFrom'],
        optionalFields: ['furnishing', 'attachedBathroom', 'foodIncluded', 'genderPreference', 'amenities'],
    },
    {
        id: 'pg',
        typeId: 'pg',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'PG',
        shortLabel: 'PG',
        shortDescription: 'Paying guest accommodation with food & housekeeping',
        description: 'Paying guest accommodation with food & housekeeping',
        icon: 'business-outline',
        status: 'ACTIVE',
        displayOrder: 4,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'occupancy', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'genderPreference', 'amenities'],
    },
    {
        id: 'coliving',
        typeId: 'coliving',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Co-living',
        shortLabel: 'Co-living',
        shortDescription: 'Fully managed community living with modern amenities',
        description: 'Fully managed community living with modern amenities',
        icon: 'sparkles-outline',
        status: 'ACTIVE',
        displayOrder: 5,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'availableFrom'],
        optionalFields: ['foodIncluded', 'furnishing', 'attachedBathroom', 'amenities'],
    },
    {
        id: 'roommate_replacement',
        typeId: 'roommate_replacement',
        parentCategory: 'stay',
        parentCategoryLabel: 'Stay',
        section: 'rent',
        displayName: 'Roommate Replacement',
        shortLabel: 'Roommate',
        shortDescription: 'Take over an existing tenancy or room in a shared flat',
        description: 'Take over an existing tenancy or room in a shared flat',
        icon: 'person-add-outline',
        status: 'ACTIVE',
        displayOrder: 6,
        consumerEnabled: true,
        postingEnabled: true,
        searchEnabled: true,
        filterEnabled: true,
        rentEnabled: true,
        saleEnabled: false,
        requiredFields: ['monthlyRent', 'deposit', 'availableFrom'],
        optionalFields: ['furnishing', 'genderPreference', 'occupancy', 'amenities'],
    },

    // ─── 2. Inactive Future Residential Categories ──────────────────────
    {
        id: '1bhk',
        typeId: '1bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'rent',
        displayName: '1 BHK',
        shortLabel: '1 BHK',
        shortDescription: '1 Bedroom Hall Kitchen Apartment or House',
        description: '1 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 7,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'availableFrom'],
        optionalFields: ['carpetArea', 'builtUpArea', 'furnishing', 'parking', 'floor', 'amenities'],
    },
    {
        id: '2bhk',
        typeId: '2bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'rent',
        displayName: '2 BHK',
        shortLabel: '2 BHK',
        shortDescription: '2 Bedroom Hall Kitchen Apartment or House',
        description: '2 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 8,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'availableFrom'],
        optionalFields: ['carpetArea', 'builtUpArea', 'furnishing', 'parking', 'floor', 'amenities'],
    },
    {
        id: '3bhk',
        typeId: '3bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'rent',
        displayName: '3 BHK',
        shortLabel: '3 BHK',
        shortDescription: '3 Bedroom Hall Kitchen Apartment or House',
        description: '3 Bedroom Hall Kitchen Apartment or House',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 9,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'availableFrom'],
        optionalFields: ['carpetArea', 'builtUpArea', 'furnishing', 'parking', 'floor', 'amenities'],
    },
    {
        id: '4bhk',
        typeId: '4bhk',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'rent',
        displayName: '4+ BHK',
        shortLabel: '4+ BHK',
        shortDescription: '4 or more Bedroom Home',
        description: '4 or more Bedroom Home',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 10,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'availableFrom'],
        optionalFields: ['carpetArea', 'builtUpArea', 'furnishing', 'parking', 'floor', 'amenities'],
    },
    {
        id: 'villa',
        typeId: 'villa',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Villa',
        shortLabel: 'Villa',
        shortDescription: 'Independent luxury villa or gated community house',
        description: 'Independent luxury villa or gated community house',
        icon: 'cube-outline',
        status: 'INACTIVE',
        displayOrder: 11,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'builtUpArea', 'availableFrom'],
        optionalFields: ['plotArea', 'furnishing', 'parking', 'amenities'],
    },
    {
        id: 'independent_house',
        typeId: 'independent_house',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Independent House',
        shortLabel: 'House',
        shortDescription: 'Standalone residential building',
        description: 'Standalone residential building',
        icon: 'home-outline',
        status: 'INACTIVE',
        displayOrder: 12,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'bedrooms', 'bathrooms', 'availableFrom'],
        optionalFields: ['builtUpArea', 'plotArea', 'furnishing', 'parking', 'amenities'],
    },
    {
        id: 'apartment',
        typeId: 'apartment',
        parentCategory: 'residential',
        parentCategoryLabel: 'Residential',
        section: 'both',
        displayName: 'Apartment',
        shortLabel: 'Apartment',
        shortDescription: 'Multi-storey residential flat or condo',
        description: 'Multi-storey residential flat or condo',
        icon: 'business-outline',
        status: 'INACTIVE',
        displayOrder: 13,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['askingPrice', 'bedrooms', 'bathrooms', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'floor', 'totalFloors', 'furnishing', 'parking', 'amenities'],
    },
    {
        id: 'plot',
        typeId: 'plot',
        parentCategory: 'land',
        parentCategoryLabel: 'Land',
        section: 'sale',
        displayName: 'Plot / Land',
        shortLabel: 'Plot',
        shortDescription: 'Residential or commercial layout plot',
        description: 'Residential or commercial layout plot',
        icon: 'map-outline',
        status: 'INACTIVE',
        displayOrder: 14,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: false,
        saleEnabled: true,
        requiredFields: ['askingPrice', 'plotArea'],
        optionalFields: ['amenities'],
    },

    // ─── 3. Inactive Future Commercial Categories ───────────────────────
    {
        id: 'office',
        typeId: 'office',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Office',
        shortLabel: 'Office',
        shortDescription: 'Commercial office workspace',
        description: 'Commercial office workspace',
        icon: 'briefcase-outline',
        status: 'INACTIVE',
        displayOrder: 15,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'floor', 'availableFrom'],
        optionalFields: ['carpetArea', 'furnishing', 'parking', 'amenities'],
    },
    {
        id: 'shop',
        typeId: 'shop',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Shop / Retail',
        shortLabel: 'Shop',
        shortDescription: 'Retail shop or showroom space',
        description: 'Retail shop or showroom space',
        icon: 'storefront-outline',
        status: 'INACTIVE',
        displayOrder: 16,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'floor', 'amenities'],
    },
    {
        id: 'commercial_space',
        typeId: 'commercial_space',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Commercial Space',
        shortLabel: 'Commercial Space',
        shortDescription: 'General commercial space or building',
        description: 'General commercial space or building',
        icon: 'business-outline',
        status: 'INACTIVE',
        displayOrder: 17,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'floor', 'amenities'],
    },
    {
        id: 'warehouse',
        typeId: 'warehouse',
        parentCategory: 'commercial',
        parentCategoryLabel: 'Commercial',
        section: 'both',
        displayName: 'Warehouse',
        shortLabel: 'Warehouse',
        shortDescription: 'Commercial warehouse or storage godown',
        description: 'Commercial warehouse or storage godown',
        icon: 'cube-outline',
        status: 'INACTIVE',
        displayOrder: 18,
        consumerEnabled: false,
        postingEnabled: false,
        searchEnabled: true,
        filterEnabled: false,
        rentEnabled: true,
        saleEnabled: true,
        requiredFields: ['monthlyRent', 'builtUpArea', 'availableFrom'],
        optionalFields: ['carpetArea', 'ceilingHeight', 'parking', 'amenities'],
    },
];

async function seedStagingTaxonomy() {
    const guard = assertStagingOnly();
    const projectId = guard.projectId;
    console.log(`[seedStagingTaxonomy] Seeding ${CANONICAL_TAXONOMY_SEEDS.length} categories to ${projectId}...`);

    const now = new Date().toISOString();

    for (const item of CANONICAL_TAXONOMY_SEEDS) {
        const docPath = `listingTaxonomy/${item.id}`;
        const docPayload = {
            ...item,
            createdAt: now,
            updatedAt: now,
            updatedBy: 'staging-seed-script',
        };
        await setDoc(projectId, docPath, docPayload);
        console.log(`  ✔ Seeded: ${item.id} (${item.displayName}) [${item.status}]`);
    }

    // Verify
    const all = await listCollection(projectId, 'listingTaxonomy');
    console.log(`[seedStagingTaxonomy] Done! Total documents in listingTaxonomy: ${all.length}`);
    const active = all.filter((d) => d.data.status === 'ACTIVE');
    const inactive = all.filter((d) => d.data.status === 'INACTIVE');
    console.log(`  Active: ${active.length} (${active.map((d) => d.id).join(', ')})`);
    console.log(`  Inactive: ${inactive.length} (${inactive.map((d) => d.id).join(', ')})`);
}

seedStagingTaxonomy().catch((err) => {
    console.error('[seedStagingTaxonomy] Failed:', err);
    process.exit(1);
});
